import type { Pet } from "@/types/pet";
import type { User } from "@/types/user";
import type { Bounty } from "@/types/bounty";
import type { Post } from "@/types/post";

export const CURRENT_USER: User = {
  id: "u1",
  username: "karmasonic",
  displayName: "Karma Sonic",
  avatarEmoji: "🦊",
  level: 12,
  xp: 2840,
  karma: 1250,
  streak: 7,
  rank: 42,
  bio: "Grinding for a better world, one bounty at a time ⚡",
  petClass: "Grinder Beast",
  bountiesCompleted: 38,
  joinedAt: "2024-01-15",
  badges: [
    { id: "b1", name: "Early Adopter", icon: "🌱", description: "Joined in the first month", earnedAt: "2024-01-15" },
    { id: "b2", name: "Streak Master", icon: "🔥", description: "7-day streak", earnedAt: "2024-06-01" },
    { id: "b3", name: "Bounty Hunter", icon: "🎯", description: "Completed 25 bounties", earnedAt: "2024-04-10" },
    { id: "b4", name: "Community Hero", icon: "🏆", description: "Top 50 on leaderboard", earnedAt: "2024-05-20" },
    { id: "b5", name: "Speed Runner", icon: "⚡", description: "Complete a bounty in under 1h", earnedAt: "2024-03-08" },
    { id: "b6", name: "Social Butterfly", icon: "🦋", description: "100 post likes received", earnedAt: "2024-05-01" },
  ],
};

export const MY_PET: Pet = {
  id: "p1",
  name: "Ryuu",
  level: 12,
  xp: 2840,
  xpToNext: 3500,
  evolution: "adult",
  class: "Grinder Beast",
  stats: { action: 78, social: 45, commerce: 32 },
  mood: "excited",
  lastFed: new Date(Date.now() - 3600000).toISOString(),
  streak: 7,
  totalBountiesCompleted: 38,
  unlockedAbilities: ["Double XP Rush", "Bounty Radar", "Karma Boost", "Iron Will"],
};

export const BOUNTIES: Bounty[] = [
  {
    id: "bnt1",
    title: "Pick up 5 pieces of trash at the park",
    description: "Help keep our local park clean. Bring a bag and collect litter around the main walking path.",
    xpReward: 50,
    karmaReward: 25,
    difficulty: "easy",
    category: "eco",
    categoryEmoji: "♻️",
    expiresAt: "2026-06-05",
    location: "City Park",
    distance: "0.3 km",
    completions: 8,
    maxCompletions: 20,
    createdBy: "u3",
    isActive: true,
  },
  {
    id: "bnt2",
    title: "Teach someone a skill you have",
    description: "Share your knowledge! Teach a friend, family member, or stranger something you're good at.",
    xpReward: 150,
    karmaReward: 80,
    difficulty: "medium",
    category: "social",
    categoryEmoji: "🧠",
    expiresAt: "2026-06-10",
    distance: "Anywhere",
    completions: 3,
    maxCompletions: 50,
    createdBy: "u2",
    isActive: true,
  },
  {
    id: "bnt3",
    title: "Complete a 5K run",
    description: "Lace up and run 5 kilometers. Track it with any fitness app and post your result.",
    xpReward: 120,
    karmaReward: 60,
    difficulty: "medium",
    category: "fitness",
    categoryEmoji: "🏃",
    expiresAt: "2026-06-04",
    distance: "0.8 km",
    completions: 15,
    maxCompletions: 100,
    createdBy: "u5",
    isActive: true,
  },
  {
    id: "bnt4",
    title: "Organize a community cleanup event",
    description: "Coordinate with at least 5 people for a neighborhood cleanup. Document with photos.",
    xpReward: 400,
    karmaReward: 250,
    difficulty: "legendary",
    category: "community",
    categoryEmoji: "🌍",
    expiresAt: "2026-06-15",
    location: "Your Neighborhood",
    distance: "1.2 km",
    completions: 1,
    maxCompletions: 5,
    createdBy: "u4",
    isActive: true,
  },
  {
    id: "bnt5",
    title: "Donate books to a local library",
    description: "Gather at least 10 books you no longer need and donate them to a library or community box.",
    xpReward: 100,
    karmaReward: 55,
    difficulty: "easy",
    category: "community",
    categoryEmoji: "📚",
    expiresAt: "2026-06-08",
    location: "Main Library",
    distance: "0.6 km",
    completions: 12,
    maxCompletions: 30,
    createdBy: "u3",
    isActive: true,
  },
  {
    id: "bnt6",
    title: "Help someone carry groceries",
    description: "Offer to help an elderly neighbor or stranger carry their groceries home.",
    xpReward: 80,
    karmaReward: 40,
    difficulty: "easy",
    category: "social",
    categoryEmoji: "🛒",
    expiresAt: "2026-06-04",
    distance: "Nearby",
    completions: 22,
    maxCompletions: 50,
    createdBy: "u2",
    isActive: true,
  },
  {
    id: "bnt7",
    title: "Plant a tree or flower",
    description: "Make your environment greener. Plant something in your garden or a community space.",
    xpReward: 200,
    karmaReward: 100,
    difficulty: "medium",
    category: "eco",
    categoryEmoji: "🌱",
    expiresAt: "2026-06-12",
    distance: "2.1 km",
    completions: 6,
    maxCompletions: 25,
    createdBy: "u1",
    isActive: true,
  },
  {
    id: "bnt8",
    title: "Volunteer at a food bank (2h)",
    description: "Spend two hours helping sort and distribute food at your local food bank.",
    xpReward: 280,
    karmaReward: 150,
    difficulty: "hard",
    category: "community",
    categoryEmoji: "🤝",
    expiresAt: "2026-06-07",
    location: "Community Center",
    distance: "1.5 km",
    completions: 4,
    maxCompletions: 10,
    createdBy: "u4",
    isActive: true,
  },
];

export const FEED_POSTS: Post[] = [
  {
    id: "post1",
    authorId: "u2",
    authorUsername: "lunavibes",
    authorEmoji: "🌙",
    authorLevel: 8,
    type: "bounty_complete",
    content: "Just helped an elderly neighbour carry 6 bags of groceries up 4 flights of stairs! 💪 The look on her face was worth more than any XP.",
    xpEarned: 80,
    likes: 47,
    comments: 12,
    liked: false,
    location: "Old Town District",
    createdAt: "2026-06-03T09:15:00Z",
  },
  {
    id: "post2",
    authorId: "u5",
    authorUsername: "neonmiku",
    authorEmoji: "✨",
    authorLevel: 10,
    type: "level_up",
    content: "LEVEL 10 UNLOCKED! 🎉 Hit the double-digits after 3 weeks of grinding. My Influencer Spirit pet just evolved to Adult stage! Who else is grinding hard this week?",
    xpEarned: 500,
    likes: 134,
    comments: 28,
    liked: true,
    createdAt: "2026-06-03T08:00:00Z",
    badge: "Level 10 Pioneer",
  },
  {
    id: "post3",
    authorId: "u3",
    authorUsername: "tradeknight",
    authorEmoji: "⚔️",
    authorLevel: 15,
    type: "achievement",
    content: "Day 21 of my cleanup streak! Picked up trash every single day this month. Small actions compound into massive karma. Keep going everyone 🌍",
    xpEarned: 50,
    bounty: BOUNTIES[0],
    likes: 89,
    comments: 19,
    liked: false,
    location: "Riverside Park",
    createdAt: "2026-06-03T07:30:00Z",
  },
  {
    id: "post4",
    authorId: "u4",
    authorUsername: "pixelrush",
    authorEmoji: "🎮",
    authorLevel: 5,
    type: "bounty_complete",
    content: "Finished my first 5K run! 28:45 — not the fastest but I actually did it. This app has me doing things I never thought I would 😅🏃",
    xpEarned: 120,
    bounty: BOUNTIES[2],
    likes: 63,
    comments: 15,
    liked: false,
    location: "West Park Trail",
    createdAt: "2026-06-02T18:45:00Z",
  },
  {
    id: "post5",
    authorId: "u2",
    authorUsername: "lunavibes",
    authorEmoji: "🌙",
    authorLevel: 8,
    type: "story",
    content: "Organized a mini skill-sharing session at the library today — taught 3 people basic Photoshop. One lady is starting a craft business! This is what KARMA is all about 🙌",
    xpEarned: 150,
    bounty: BOUNTIES[1],
    likes: 201,
    comments: 34,
    liked: false,
    location: "Main Library",
    createdAt: "2026-06-02T14:20:00Z",
  },
  {
    id: "post6",
    authorId: "u5",
    authorUsername: "neonmiku",
    authorEmoji: "✨",
    authorLevel: 10,
    type: "bounty_complete",
    content: "Donated 23 books to the community shelf today 📚 Cleaned out my whole shelf — someone else's adventure starts now!",
    xpEarned: 100,
    bounty: BOUNTIES[4],
    likes: 55,
    comments: 8,
    liked: true,
    location: "Corner Library Box",
    createdAt: "2026-06-01T11:00:00Z",
  },
];

export const SHOP_ITEMS = [
  {
    id: "s1",
    emoji: "🍖",
    name: "Premium Pet Meal",
    description: "Feed your pet a legendary meal. +50 mood and +20 XP bonus for 24h.",
    price: 150,
    category: "pet",
    rarity: "rare",
    tag: "BEST SELLER",
  },
  {
    id: "s2",
    emoji: "⚡",
    name: "XP Booster",
    description: "Double XP from all bounties for 2 hours. Stack with streaks.",
    price: 300,
    category: "power",
    rarity: "epic",
    tag: "HOT",
  },
  {
    id: "s3",
    emoji: "🎨",
    name: "Pet Skin: Neon",
    description: "Give your companion a glowing neon look. Pure flex.",
    price: 500,
    category: "cosmetics",
    rarity: "legendary",
    tag: "NEW",
  },
  {
    id: "s4",
    emoji: "🎯",
    name: "Bounty Scanner",
    description: "Reveals 5 hidden bounties in your area. 24h duration.",
    price: 200,
    category: "power",
    rarity: "uncommon",
    tag: null,
  },
  {
    id: "s5",
    emoji: "🛡️",
    name: "Streak Shield",
    description: "Protect your streak from breaking for one day.",
    price: 100,
    category: "power",
    rarity: "common",
    tag: null,
  },
  {
    id: "s6",
    emoji: "🏠",
    name: "Pet Habitat: Forest",
    description: "Upgrade your pet's home to a lush mystical forest.",
    price: 750,
    category: "pet",
    rarity: "legendary",
    tag: "LIMITED",
  },
  {
    id: "s7",
    emoji: "💊",
    name: "Mood Potion",
    description: "Instantly restore your pet's mood to MAX HAPPY.",
    price: 75,
    category: "pet",
    rarity: "common",
    tag: null,
  },
  {
    id: "s8",
    emoji: "🌟",
    name: "Karma Multiplier",
    description: "All karma earned is multiplied by 1.5x for 12 hours.",
    price: 400,
    category: "power",
    rarity: "epic",
    tag: null,
  },
];

export const MAP_PINS = [
  { id: "m1", type: "bounty", emoji: "🎯", x: 20, y: 25, label: "Trash Pickup", xp: 50 },
  { id: "m2", type: "bounty", emoji: "🎯", x: 55, y: 40, label: "5K Run", xp: 120 },
  { id: "m3", type: "event", emoji: "⚡", x: 35, y: 60, label: "XP Sprint", xp: 200 },
  { id: "m4", type: "player", emoji: "👤", x: 65, y: 30, label: "tradeknight", xp: 0 },
  { id: "m5", type: "player", emoji: "👤", x: 45, y: 70, label: "lunavibes", xp: 0 },
  { id: "m6", type: "hotspot", emoji: "🔴", x: 75, y: 55, label: "Karma Zone", xp: 500 },
  { id: "m7", type: "bounty", emoji: "🎯", x: 15, y: 75, label: "Book Donation", xp: 100 },
  { id: "m8", type: "event", emoji: "⚡", x: 80, y: 20, label: "Community Day", xp: 300 },
  { id: "m9", type: "player", emoji: "👤", x: 30, y: 45, label: "neonmiku", xp: 0 },
];

export const LEADERBOARD = [
  { rank: 1, username: "zenmaster", emoji: "🧘", level: 28, karma: 8940, class: "Influencer Spirit" },
  { rank: 2, username: "ironforge", emoji: "⚒️", level: 25, karma: 7650, class: "Grinder Beast" },
  { rank: 3, username: "goldpath", emoji: "💰", level: 22, karma: 6200, class: "Merchant King" },
  { rank: 41, username: "tradeknight", emoji: "⚔️", level: 15, karma: 3500, class: "Merchant King" },
  { rank: 42, username: "karmasonic", emoji: "🦊", level: 12, karma: 1250, class: "Grinder Beast" },
  { rank: 43, username: "neonmiku", emoji: "✨", level: 10, karma: 1180, class: "Influencer Spirit" },
];
