import type { World } from "@/types/world";

export const WORLDS: World[] = [
  {
    id: "cosmic",
    name: "COSMIC",
    tagline: "Universum & stjärnor",
    emoji: "🌌",
    accent: "#a855f7",
    glowColor: "#a855f744",
    bg: "#0f0520",
    petRoomBg: "linear-gradient(180deg, #0f0520 0%, #1a0840 100%)",
    petRoomEmojis: ["⭐", "🪐", "🌙", "✨", "🔭", "🛸"],
  },
  {
    id: "nature",
    name: "NATURE",
    tagline: "Skog & natur",
    emoji: "🌿",
    accent: "#22c55e",
    glowColor: "#22c55e44",
    bg: "#0a1a0a",
    petRoomBg: "linear-gradient(180deg, #0a2010 0%, #142a14 100%)",
    petRoomEmojis: ["🌳", "🍄", "🌸", "🦋", "🌱", "🍃"],
  },
  {
    id: "city",
    name: "CITY",
    tagline: "Neon city vibes",
    emoji: "🏙️",
    accent: "#00e5ff",
    glowColor: "#00e5ff44",
    bg: "#001a2a",
    petRoomBg: "linear-gradient(180deg, #001a2a 0%, #002a3a 100%)",
    petRoomEmojis: ["🏙️", "🚕", "💡", "📡", "🎵", "🌉"],
  },
  {
    id: "pixel",
    name: "PIXEL",
    tagline: "8-bit retro pixel",
    emoji: "🎮",
    accent: "#ff6b35",
    glowColor: "#ff6b3544",
    bg: "#1a0a00",
    petRoomBg: "linear-gradient(180deg, #1a0a00 0%, #2a1200 100%)",
    petRoomEmojis: ["🎮", "👾", "🕹️", "💾", "🏆", "⚡"],
  },
  {
    id: "ocean",
    name: "OCEAN",
    tagline: "Djuphavsäventyr",
    emoji: "🌊",
    accent: "#06b6d4",
    glowColor: "#06b6d444",
    bg: "#001428",
    petRoomBg: "linear-gradient(180deg, #001428 0%, #002850 100%)",
    petRoomEmojis: ["🐬", "🦈", "🐠", "🦀", "🐙", "🌊"],
  },
  {
    id: "volcano",
    name: "VOLCANO",
    tagline: "Elddungen brinner",
    emoji: "🌋",
    accent: "#ef4444",
    glowColor: "#ef444444",
    bg: "#1a0500",
    petRoomBg: "linear-gradient(180deg, #1a0500 0%, #3a0a00 100%)",
    petRoomEmojis: ["🌋", "🔥", "💎", "⚡", "🏔️", "🌡️"],
  },
  {
    id: "sky",
    name: "SKY",
    tagline: "Molnens rike",
    emoji: "☁️",
    accent: "#38bdf8",
    glowColor: "#38bdf844",
    bg: "#0c2040",
    petRoomBg: "linear-gradient(180deg, #0c2040 0%, #1a3060 100%)",
    petRoomEmojis: ["☁️", "🦅", "⭐", "🌈", "🎈", "🌤️"],
  },
  {
    id: "neon",
    name: "NEON",
    tagline: "Cyberpunk drömmar",
    emoji: "🌆",
    accent: "#f0abfc",
    glowColor: "#f0abfc44",
    bg: "#0a0014",
    petRoomBg: "linear-gradient(180deg, #0a0014 0%, #180028 100%)",
    petRoomEmojis: ["🌆", "💜", "🤖", "💡", "🎵", "🔮"],
  },
  {
    id: "crystal",
    name: "CRYSTAL",
    tagline: "Is & diamanter",
    emoji: "💎",
    accent: "#67e8f9",
    glowColor: "#67e8f944",
    bg: "#050f28",
    petRoomBg: "linear-gradient(180deg, #050f28 0%, #0a1a40 100%)",
    petRoomEmojis: ["💎", "❄️", "🔮", "⭐", "💠", "🌟"],
  },
  {
    id: "shadow",
    name: "SHADOW",
    tagline: "Mörkrets krafter",
    emoji: "🌑",
    accent: "#a78bfa",
    glowColor: "#a78bfa44",
    bg: "#050008",
    petRoomBg: "linear-gradient(180deg, #050008 0%, #0a0018 100%)",
    petRoomEmojis: ["🌑", "🕷️", "💀", "🦇", "👁️", "🌫️"],
  },
];

export const WORLD_STORAGE_KEY = "karma_world_v1";

export function getWorld(id: string): World {
  return WORLDS.find(w => w.id === id) ?? WORLDS[2];
}
